version: '3.8'

services:
  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./docker-database/postgresql:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env
    networks:
      - backend
  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - ./docker-database/redis:/data
    env_file:
      - .env
    networks:
      - backend
  meme-coin-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_ENV=development
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}
      - REDIS_URL=redis://${REDIS_PASSWORD}@redis:6379/0?protocol=3
    ports:
      - '8080:8080'
    networks:
      - backend
    depends_on:
      - postgresql
      - redis
    restart: on-failure
networks:
  backend:
    driver: bridge
