version: '3.8'

services:
  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./docker-database/postgresql:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env
  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - ./docker-database/redis:/data
    env_file:
      - .env
    depends_on:
      - postgresql
