// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	"os"
	"path"

	"github.com/swaggo/swag"
)

func init() {
	dir, _ := os.Getwd()
	docPath := path.Join(dir, "api", "swagger.yaml")
	docContent, _ := os.ReadFile(docPath)

	// SwaggerInfo holds exported Swagger Info so clients can modify it
	var SwaggerInfo = &swag.Spec{
		Version:          "1.0",
		Host:             "localhost:8080",
		BasePath:         "/v1/meme-coin/",
		Schemes:          []string{},
		Title:            "MemeCoin API",
		Description:      "This is a simple API for MemeCoin",
		InfoInstanceName: "swagger",
		SwaggerTemplate:  string(docContent),
		LeftDelim:        "{{",
		RightDelim:       "}}",
	}
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
